name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 10th minute
    - cron: "*/10 * * * *"
      
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""
